apiVersion: backstage.io/v1alpha1
kind: System
metadata:
    name: capsule
    description: Primary catalog file for demo thingy
    title: Capsule
    tags:
      - ember
      - scala
spec:
    owner: group:development-team
    domain: capsule